### ISSUE TITLE
bug about the USER directive

### ISSUE THREAD

**Issue by k3ck3c** [CenturyLinkLabs/dockerfile-from-image#9]
a buglet

When launching 

docker run -v /var/run/docker.sock:/var/run/docker.sock   centurylink/dockerfile-from-image k3ck3c/captvty

I get, among other things

USER [gg]

when it should be 

USER gg

of course the created Dockerfile does not work, as this is not a "legal" user.

Thanks for this great tool.

**Comment by ozbillwang** [comment]
Nice finding.

I didn't see the same problem with https://imagelayers.io/?images=k3ck3c%2Fcaptvty:latest, it shows properly.

**Comment by ozbillwang** [comment]
I have duplicated the issue

```
$ cat Dockerfile
FROM ruby
USER gg

$ docker build -t test .
Sending build context to Docker daemon 2.048 kB
Step 1 : FROM ruby
 ---> a930a50e60f8
Step 2 : USER gg
 ---> Using cache
 ---> db680ba9a608
Successfully built db680ba9a608

$ dfimage test
FROM ruby:latest
USER [gg]
```

So we need add one `if-else` statement as https://github.com/CenturyLinkLabs/dockerfile-from-image/blob/master/dockerfile-from-image.rb#L56 to remove `[]` from USER command.

**Comment by ozbillwang** [comment]
pull request  #10 has been raised for this issue, waiting for approval.

**Comment by davidgardner11** [comment]
@k3ck3c @SydOps - After merging PR  https://github.com/CenturyLinkLabs/dockerfile-from-image/pull/10, I confirmed that the [ ] issue is resolved

docker run -v /var/run/docker.sock:/var/run/docker.sock centurylink/dockerfile-from-image test
FROM ruby:latest
USER gg

**Comment by k3ck3c** [comment]
Thanks for your time
